src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 10, unique: true)]
    private ?string $matricule = null;

    #[ORM\Column(length: 255)]
    private ?string $marque_type = null;

    #[ORM\Column(length: 50)]
    private ?string $numSerie = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $carosserie = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $puissance = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateEmission = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $usageVehicule = null;

    #[ORM\Column(length: 5, nullable: true)]
    private ?string $energie = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $place = null;

    #[ORM\OneToMany(mappedBy: 'vehicule', targetEntity: Assurance::class)]
    private Collection $assurances;

    public function __construct()
    {
        $this->assurances = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    public function setMatricule(string $matricule)
    {
        $this->matricule = $matricule;

        return $this;
    }

    public function getMarqueType(): ?string
    {
        return $this->marque_type;
    }

    public function setMarqueType(string $marque_type)
    {
        $this->marque_type = $marque_type;

        return $this;
    }

    public function getNumSerie(): ?string
    {
        return $this->numSerie;
    }

    public function setNumSerie(string $numSerie)
    {
        $this->numSerie = $numSerie;

        return $this;
    }

    public function getCarosserie(): ?string
    {
        return $this->carosserie;
    }

    public function setCarosserie(?string $carosserie)
    {
        $this->carosserie = $carosserie;

        return $this;
    }

    public function getPuissance(): ?string
    {
        return $this->puissance;
    }

    public function setPuissance(?string $puissance)
    {
        $this->puissance = $puissance;

        return $this;
    }

    public function getDateEmission(): ?\DateTimeInterface
    {
        return $this->dateEmission;
    }

    public function setDateEmission(\DateTimeInterface $dateEmission)
    {
        $this->dateEmission = $dateEmission;

        return $this;
    }

    public function getUsageVehicule(): ?string
    {
        return $this->usageVehicule;
    }

    public function setUsageVehicule(?string $usageVehicule)
    {
        $this->usageVehicule = $usageVehicule;

        return $this;
    }

    public function getEnergie(): ?string
    {
        return $this->energie;
    }

    public function setEnergie(?string $energie)
    {
        $this->energie = $energie;

        return $this;
    }

    public function getPlace(): ?int
    {
        return $this->place;
    }

    public function setPlace(int $place)
    {
        $this->place = $place;

        return $this;
    }

    /**
     * @return Collection<int, Assurance>
     */
    public function getAssurances(): Collection
    {
        return $this->assurances;
    }

    public function addAssurance(Assurance $assurance)
    {
        if (!$this->assurances->contains($assurance)) {
            $this->assurances->add($assurance);
            $assurance->setVehicule($this);
        }

        return $this;
    }

    public function removeAssurance(Assurance $assurance)
    {
        if ($this->assurances->removeElement($assurance)) {
            // set the owning side to null (unless already changed)
            if ($assurance->getVehicule() === $this) {
                $assurance->setVehicule(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getMatricule() . " -  " . $this->getMarqueType(); 
    }
}

src/Controller/VehiculeController.php
<?php

namespace App\Controller;

use App\Entity\Vehicule;
use App\Form\VehiculeFormType;
use App\Repository\VehiculeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/vehicule')]
class VehiculeController extends AbstractController
{
    private $menu = 'vehicule';

    #[Route('/', name: 'app_vehicule')]
    public function index(VehiculeRepository $vehiculeRepository): Response
    {
        $vehicules = $vehiculeRepository->findAll();

        return $this->render('vehicule/index.html.twig', [
            'menu' => $this->menu,
            'vehicules' => $vehicules, 
        ]);
    }

    #[Route('/add', name: 'app_AddVehicule', methods: ['GET', 'POST'])]
    public function addVehicule(Request $request, EntityManagerInterface $em): Response
    {
        $vehicule = new Vehicule();
        $form = $this->createForm(VehiculeFormType::class, $vehicule);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($vehicule);
            $em->flush();

            return $this->redirectToRoute('app_vehicule'); // Redirige vers la liste des clients par exemple
        }

        return $this->render('vehicule/form.html.twig', [
            'form' => $form->createView(),
            'menu' => $this->menu,
        ]);
    }

    #[Route('/edit/{id}', name: 'app_EditVehicule')]
    public function editClient(Request $request, Vehicule $vehicule, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(VehiculeFormType::class, $vehicule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_vehicule'); // Redirige vers la liste des clients par exemple
        }

        return $this->render('vehicule/form.html.twig', [
            'form' => $form->createView(),
            'vehicule' => $vehicule,
            'menu' => $this->menu,
        ]);
    }

    #[Route('/delete/{id}', name: 'app_DeleteVehicule')]
    public function deleteVehicule(Request $request, Vehicule $vehicule, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$vehicule->getId(), $request->request->get('_token'))) {
            $entityManager->remove($vehicule);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_vehicule');
    }
}

templates/vehicule/form.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<title>Assurance ARO</title>
	<meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />

	<!-- Styles -->
	{% include 'partials/styles.html.twig' %}
</head>
<body>
	<div class="wrapper">
		<!-- Navbar Header -->
		{% include 'partials/navbar_header.html.twig' %}

		<!-- Sidebar -->
		{% include 'partials/sidebar.html.twig' %}

		<div class="main-panel">
			<div class="content">
				<div class="page-inner">
					<div class="page-header">
						<h4 class="page-title">Formulaire véhicules</h4>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="card">
								{{ form_start(form) }}
									<div class="card-header">
										<div class="card-title">Véhicules</div>
									</div>
									<div class="card-body">
										
										<div class="form-group">
											{{ form_label(form.matricule) }}
											{{ form_widget(form.matricule, {'attr': {'class': 'form-control', 'placeholder': 'Matricule'}}) }}
										</div>
										<div class="form-group">
											{{ form_label(form.marque_type) }}
											{{ form_widget(form.marque_type, {'attr': {'class': 'form-control', 'placeholder': 'Marque et type'}}) }}
										</div>
										<div class="form-group">
											{{ form_label(form.numSerie) }}
											{{ form_widget(form.numSerie, {'attr': {'class': 'form-control', 'placeholder': 'Numero de série'}}) }}
										</div>
										<div class="form-group">
											{{ form_label(form.carosserie) }}
											{{ form_widget(form.carosserie, {'attr': {'class': 'form-control', 'placeholder': 'Carosserie'}}) }}
										</div>
                                        <div class="form-group">
											{{ form_label(form.puissance) }}
											{{ form_widget(form.puissance, {'attr': {'class': 'form-control', 'placeholder': 'Puissance'}}) }}
										</div>
										<div class="form-group">
											{{ form_label(form.dateEmission) }}
											{{ form_widget(form.dateEmission, {'attr': {'class': 'form-control', 'placeholder': 'Date d emission'}}) }}
										</div>
										<div class="form-group">
											{{ form_label(form.usageVehicule) }}
											{{ form_widget(form.usageVehicule, {'attr': {'class': 'form-control', 'placeholder': 'Usage'}}) }}
										</div>
										<div class="form-group">
											{{ form_label(form.energie) }}
											{{ form_widget(form.energie, {'attr': {'class': 'form-control', 'placeholder': 'Energie'}}) }}
										</div>
                                        <div class="form-group">
											{{ form_label(form.place) }}
											{{ form_widget(form.place, {'attr': {'class': 'form-control', 'placeholder': 'Place'}}) }}
										</div>
										
									</div>
									<div class="card-action">
										<button type="submit" class="btn btn-success">Enregistrer</button>
										<a href="{{ path('app_vehicule') }}" class="btn btn-danger">Annuler</a>
									</div>
								{{ form_end(form) }}
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>

	</div>
	
	{% include 'partials/javascript.html.twig' %}  
</body>
</html>

templates/vehicule/index.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<title>Assurance ARO</title>
	<meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />

	<!-- Styles -->
	{% include 'partials/styles.html.twig' %}
</head>
<body>
	<div class="wrapper">
		<!-- Navbar Header -->
		{% include 'partials/navbar_header.html.twig' %}

		<!-- Sidebar -->
		{% include 'partials/sidebar.html.twig' %}

        <div class="main-panel">
            <div class="content">
                <div class="page-inner">
                    <div class="page-header">
                        <h4 class="page-title">Listes des véhicules</h4>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
								<div class="card-header">
									<div class="d-flex align-items-center">
										<a href="{{ path('app_AddVehicule') }}">
											<button class="btn btn-primary btn-round ml-auto">
												<i class="fa fa-plus"></i>
												Ajouter un vehicule 
											</button>
										</a>
									</div>
								</div>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <table id="add-row" class="display table table-striped table-hover" >
                                            <thead>
                                                <tr>
                                                    <th>Matricule</th>
                                                    <th>Marque et type</th>
                                                    <th>N°  de Série</th>
                                                    <th>Carosserie</th>
                                                    <th>Puissance</th>
                                                    <th>Date d'émission en cirulation</th>
                                                    <th>Usage</th>
                                                    <th>Source d'énergie</th>
                                                    <th>Nbre de places</th>
                                                    <th style="width: 10%"></th>
                                                </tr>
                                            </thead>
                                            <tfoot>
                                                <tr>
                                                    <th>Matricule</th>
                                                    <th>Marque et type</th>
                                                    <th>N°  de Série</th>
                                                    <th>Carosserie</th>
                                                    <th>Puissance</th>
                                                    <th>Date d'émission en cirulation</th>
                                                    <th>Usage</th>
                                                    <th>Source d'énergie</th>
                                                    <th>Nbre de places</th>
                                                    <th>Action</th>
                                                </tr>
                                            </tfoot>
                                            <tbody>
                                                {% for vehicule in vehicules %}
                                                    <tr>
														<td> {{ vehicule.matricule }} </td>
														<td> {{ vehicule.marqueType }} </td>
														<td> {{ vehicule.numSerie }} </td>
														<td> {{ vehicule.carosserie }} </td>
                                                        <td> {{ vehicule.puissance }} </td>
														<td> {{ vehicule.dateEmission ? vehicule.dateEmission|date('Y-m-d') : '' }} </td>
														<td> {{ vehicule.usageVehicule }} </td>
														<td> {{ vehicule.energie }} </td>
                                                        <td> {{ vehicule.place }} </td>
														<td>
															<div class="form-button-action">
																<button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-primary btn-lg" data-original-title="Modifier vehicule">
																	<a href="{{ path('app_EditVehicule', {'id': vehicule.id}) }}">
																		<i class="fa fa-edit"></i>
																	</a>
																</button>

																<form method="post" action="{{ path('app_DeleteVehicule', {'id': vehicule.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
																	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vehicule.id) }}">
																	<button type="submit" data-toggle="tooltip" title="" class="btn btn-link btn-danger" data-original-title="Supprimer vehicule">
																		<i class="fa fa-times"></i>
																	</button>
																</form>
																
															</div>
														</td>
													</tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

	</div>
	
	{% include 'partials/javascript.html.twig' %}  

    <script >
		$(document).ready(function() {
			$('#basic-datatables').DataTable({
			});

			$('#multi-filter-select').DataTable( {
				"pageLength": 5,
				initComplete: function () {
					this.api().columns().every( function () {
						var column = this;
						var select = $('<select class="form-control"><option value=""></option></select>')
						.appendTo( $(column.footer()).empty() )
						.on( 'change', function () {
							var val = $.fn.dataTable.util.escapeRegex(
								$(this).val()
								);

							column
							.search( val ? '^'+val+'$' : '', true, false )
							.draw();
						} );

						column.data().unique().sort().each( function ( d, j ) {
							select.append( '<option value="'+d+'">'+d+'</option>' )
						} );
					} );
				}
			});

			// Add Row
			$('#add-row').DataTable({
				"pageLength": 5,
			});

			var action = '<td> <div class="form-button-action"> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-primary btn-lg" data-original-title="Edit Task"> <i class="fa fa-edit"></i> </button> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-danger" data-original-title="Remove"> <i class="fa fa-times"></i> </button> </div> </td>';

			$('#addRowButton').click(function() {
				$('#add-row').dataTable().fnAddData([
					$("#addName").val(),
					$("#addPosition").val(),
					$("#addOffice").val(),
					action
					]);
				$('#addRowModal').modal('hide');

			});
		});
	</script>
</body>
</html>